wandb_version: 1

nlayers:
  desc: null
  value: 3
lambda_s:
  desc: null
  value: 20
lambda_v:
  desc: null
  value: 2
lambda_l2:
  desc: null
  value: 0.0005
lambda_pg:
  desc: null
  value: 0.001
tau:
  desc: null
  value: 0.2
lr:
  desc: null
  value: 0.1
max_epochs:
  desc: null
  value: 1000
condnet_min_prob:
  desc: null
  value: 0.1
condnet_max_prob:
  desc: null
  value: 0.7
learning_rate:
  desc: null
  value: 0.1
BATCH_SIZE:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693317105.788483
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.17
      5: 0.15.8
      8:
      - 3
      - 5
